### ISSUE TITLE
[Request] Create Vimdoc

### ISSUE THREAD

**Issue by miversen33** [ziontee113/icon-picker.nvim#1]
Please consider creating a simple vimdoc for your plugin so that we can view its commands from `:help`

**Comment by ziontee113** [comment]
Thank you for the suggestion. I’ll look into how to do help docs :)

**Comment by miversen33** [comment]
No problem! Here are a few resources I used when creating them for myself
[Learn Vimscript The Hard Way](https://learnvimscriptthehardway.stevelosh.com/chapters/54.html)
[Also feel free to steal mine and change it to fit yours project](https://github.com/miversen33/netman.nvim/blob/main/doc/netman.txt)

**Comment by ziontee113** [comment]
Thanks. Simple help docs is online. Let me know what you think. Is there something else I should add? This is a quite simple plugin.

**Comment by miversen33** [comment]
Looks good! I don't think much need to be there, just having _something_ within vim that calls out what the available commands are for `icon-picker.nvim` so I dont need to come back to github or look at the source code. Thanks!

**Comment by ziontee113** [comment]
Thank you :) Have a good day man.
