### ISSUE TITLE
Enhancement request: add all available sources by default

### ISSUE THREAD

**Issue by mario-amazing** [ziontee113/icon-picker.nvim#10]
Could you add by default all sources are turned on:
`:IconPickerInsert emoji nerd_font alt_font symbols == :IconPickerInsert`
I have this default config:
`require("icon-picker").setup({ disable_legacy_commands = true })`
<img width="393" alt="image" src="https://user-images.githubusercontent.com/9537753/187073316-d1975837-a9d9-4a69-96d5-fff682d3ae9c.png">
<img width="217" alt="image" src="https://user-images.githubusercontent.com/9537753/187073325-6db195cc-63f1-404c-b355-3716e3464abc.png">

And update documentation for it

**Comment by ziontee113** [comment]
Thank you for the suggestion. I’ll look into it.

**Comment by ziontee113** [comment]
Hi @mario-amazing , this feature has been implemented. Please update the plugin :)

**Comment by mario-amazing** [comment]
Thanks!
P.S. maybe add `disable_legacy_commands = true `to default config as well
