### ISSUE TITLE
Fix icons indentation

### ISSUE THREAD

**Issue by mario-amazing** [ziontee113/icon-picker.nvim#11]
Could you fix icons indentation?
<img width="282" alt="Screenshot 2022-08-29 at 11 23 46" src="https://user-images.githubusercontent.com/9537753/187147728-3b4a7f93-33bb-4f6a-ba09-42713665a517.png">
<img width="322" alt="Screenshot 2022-08-29 at 11 23 20" src="https://user-images.githubusercontent.com/9537753/187147741-7513a175-9e07-4703-ba16-5c5bbe1d5b26.png">

**Comment by ziontee113** [comment]
Those are problems with font ligatures that's out of my ability to fix.

**Comment by mario-amazing** [comment]
As I can see in another plugin, even with different icon sizes, it can have proper padding
  <img alt="" src="https://user-images.githubusercontent.com/9537753/187185247-22216393-6ce3-43dc-8a3f-4dbaa1933bf0.png" height="450">

**Comment by ziontee113** [comment]
It's because of emojis and font ligatures, I won't be able to provide help here.
