### ISSUE TITLE
Duplication of a letter during a search

### ISSUE THREAD

**Issue by mario-amazing** [ziontee113/icon-picker.nvim#12]
Preview bug with a duplicated letter in stickers:
Without search:
<img width="308" alt="Screenshot 2022-08-29 at 11 41 04" src="https://user-images.githubusercontent.com/9537753/187149962-37fc6d6a-4674-41d2-8c27-af4de1048960.png">
bug:
<img width="279" alt="Screenshot 2022-08-29 at 11 41 26" src="https://user-images.githubusercontent.com/9537753/187149984-3fe68a1c-8f5e-4a4a-b9c1-387a4c96cfa6.png">
<img width="303" alt="Screenshot 2022-08-29 at 11 41 47" src="https://user-images.githubusercontent.com/9537753/187150011-805dee7d-1d9d-4126-8b30-87a279ded3ca.png">

**Comment by ziontee113** [comment]
Those are not bugs. They're part of the icons data set to help with fuzzy finding.

**Comment by mario-amazing** [comment]
So why in preview “hook” converts to “hookk” in search? And only when searching emoji

**Comment by ziontee113** [comment]
![Screenshot from 2022-08-29 18-08-46](https://user-images.githubusercontent.com/102876811/187188484-47a843cc-dea8-435d-82e2-277ba81c3db6.png)
It works fine for me. Hmm...

**Comment by ziontee113** [comment]
>So why in preview “hook” converts to “hookk” in search? And only when searching emoji

There's a high change it's a visual glitch related font ligatures in Terminal Emulators. It's not related to this plugin.

**Comment by mario-amazing** [comment]
Maybe you know how can I fix it?

**Comment by ziontee113** [comment]
Sorry, I don't know. I also have the same visual glitches. I just don't mind them too much.
