### ISSUE TITLE
update material design icons to nerd v3.0.0

### ISSUE THREAD

**Issue by inhake2** [ziontee113/icon-picker.nvim#15]
The use of patched fonts with nerd-icons v3.0.0 leads to some icons being displayed badly or not at all.
Both code points and class names have changed.

Informations [here](https://github.com/ryanoasis/nerd-fonts/releases)

Also, it seems that the list of icons is not up to date.
From the [i_md.sh script](https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/lib/i_md.sh) it is simple to update  nf-icon-list.lua. Some icons are not available anymore.

As it's a breaking change that can be annoying for people using nerd-fonts < v3.0.0 and I'm not sure you want to integrate all these changes, I don't propose a PR. I can do that (first time) if you’re ok with these changes.

Maybe you should provide a v3.0.0 branch ?

**Comment by ziontee113** [comment]
Thank you @softnomics for bringing this to my attention.

Base on your sh script link, I added a new command argument `nerd_font_v3` at e6dca182518eeb7a51470c13605a5bce08a816e4.
You can try out `IconPickerNormal nerd_font_v3` too see if it works. I don't have V3 installed so I have no idea if this is gonna work for you.

**Comment by inhake2** [comment]
It seems to be a good compromise instead of breaking older nerd font users.
Maybe you’ll have to reconsider it later when V3 will be largely use.

Everything seems to work very well for me !

Thanks a lot @ziontee113

**Comment by ziontee113** [comment]
I'm closing this issue for now. Feel free to re-open it if necessary :+1:
