### ISSUE TITLE
what's your setup

### ISSUE THREAD

**Issue by stumash** [ziontee113/icon-picker.nvim#16]
that first screenshot (right under the two screencapture videos) in the README is sooo crispy

what font is that? what terminal are you using? how did you get it to be so sharp?

my neovim is not as pretty when I have popup floats like the icon-picker one in that screenshot :(

**Comment by ziontee113** [comment]
I used that setup a long time ago, so I don't remember the exact set up I was using back then.
Colorscheme you can look up `nightfly`, I use kitty terminal. The font seems to be `Meslo` or `Caskaydia Cove`.

**Comment by smashaal** [comment]
thank you!!

you can close this
