### ISSUE TITLE
Search is still showing already removed/deprecated icons from nerd-font

### ISSUE THREAD

**Issue by saessugo** [ziontee113/icon-picker.nvim#17]
Not quite sure if this belongs here, but didn't find any other place to post this
When I search for a font it show  deprecated/removed icons, especifically the nf-mdi ones.
![image](https://github.com/ziontee113/icon-picker.nvim/assets/29466915/820842b6-3dc4-4574-a262-290ae9139372)

**Comment by ziontee113** [comment]
If you're using Nerd Fonts V3, you could run a command like this instead:

`:IconPickerInsert emoji nerd_font_v3 alt_font symbols`

I'm still on older version of Nerd Fonts so I can't verify this. You can try this out and see if it works.

**Comment by saessugo** [comment]
Yes, this will exclude the depricated icons...
Just if this helps this my updated keymap
`
keymap("n", "<leader><leader>i", "<cmd>IconPickerNormal emoji nerd_font_v3 alt_font symbols<cr>", term_opts)
keymap("n", "<leader><leader>y", "<cmd>IconPickerYank emoji nerd_font_v3 alt_font symbols<cr>", term_opts)
keymap("i", "<C-i>", "<cmd>IconPickerInsert emoji nerd_font_v3 alt_font symbols<cr>", term_opts)
`
