### ISSUE TITLE
Newer nerdfonts icons missing

### ISSUE THREAD

**Issue by Snxwman** [ziontee113/icon-picker.nvim#19]
Some of the newer icons from nerdfonts are missing from the tables. 

For example, the neovim icons `nf-custom-neovim` and `nf-linux-neovim`.

Is there a script to regenerate the icon tables or are entries added manually?

**Comment by ziontee113** [comment]
Hi @Snxwman, I'm currently busy right now and I'm still on Nerd Fonts V2.

In this repo, the icon list for V3 is in the file `nf-v3-icon-list.lua`.

I worked on this issue a while back https://github.com/ziontee113/icon-picker.nvim/issues/15. PRs are welcome.

**Comment by Snxwman** [comment]
Hi, thanks for the reply. I'll take a look. 

Is the `nf-v3-icon-list.lua` file generated or hand written?

**Comment by ziontee113** [comment]
If I remember correctly I just used Vim macros to edit this file https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/lib/i_md.sh into a Lua file.
