### ISSUE TITLE
Suggested insert mode mapping (`<C-i>`) inserts `<Tab>` instead of opening the picker

### ISSUE THREAD

**Issue by Gelio** [ziontee113/icon-picker.nvim#2]
Hey, thanks for creating this plugin! I didn't know I needed it :smile: 

When I wanted to try it out, the insert mode mapping suggested in the README didn't work for me. It inserted a Tab instead. It turns out that [`C-i` is sent as `<Tab>` from the terminal to vim](https://unix.stackexchange.com/a/563480/490740). Even though the mapping was listed in `:imap <C-i>`, Tab was inserted instead of opening the emoji picker.

I was able to use `<C-o>:PickIconsInsert<CR>` in insert mode, so it was up to the `<C-i>` mapping that was sent as `<Tab>` by the terminal.

I reckon I may not be the only one with this problem. Perhaps changing the default insert-mode binding to `<C-e>` will let other users avoid this problem.

For reference, I am using kitty as my terminal

```sh
19:27 $ kitty -v
kitty 0.25.2 created by Kovid Goyal
```

I also checked in `gnome-terminal` and it also sent `<C-i>` as `<Tab>`.

**Comment by ziontee113** [comment]
Oh hi! You can check out my 3 minute video to resolve this problem for your terminal emulator
https://www.youtube.com/watch?v=lHBD6pdJ-Ng

I mapped it to C-I because in my mind it's "Icon". I'll consider adding more info on the README

**Comment by Gelio** [comment]
Thanks for sharing the video. It is a funny coincidence, Youtube recommended that video to me yesterday in the morning (before I saw this plugin) but I didn't watch it :sweat_smile: 

Sure, I agree that `C-i` makes sense here as _i_ can stand for _icon_. It may not be a welcome default for many people though, so I guess we can add a note about `C-i` needing special terminal configuration and/or change the default to something else.

I tried adding a mapping for `C-i` in my kitty config and I am now able to use `<C-i>` for `:PickIconsInsert` :tada: Thanks for sharing the solution

**Comment by Gelio** [comment]
I see you added a note about binding `<C-i>` to the README. In my view, that is enough to consider this issue addressed. I will close the issue

**Comment by ziontee113** [comment]
Glad it helped :)
