### ISSUE TITLE
Plug packadge

### ISSUE THREAD

**Issue by godalming123** [ziontee113/icon-picker.nvim#5]
Is it possible to install with vim-plug

**Comment by ziontee113** [comment]
It should be.
Something like `Plug 'ziontee113/icon-picker.nvim'`
Remember to have `require("icon-picker")` after you install it.

Are you using init.lua or init.vim?

**Comment by godalming123** [comment]
will try

**Comment by godalming123** [comment]
Plug appears to work fine but I get a 7000 icon list that I have to page down to the end to see the help text however I believe this is vim's behavior and I need to install something like dressing to get a more accessible menu, please correct me if I am wrong.
Could you also please add plug to the list of plugin options and fix the demo config in the readme. it should be `PickEverythingInsert` instead of `PickInsert`

**Comment by ziontee113** [comment]
Noted. Thank you for opening the issue.
And yes, you do need something like dressing.nvim and a fuzzy finder like Telescope or FZF Lua to use this.
