### ISSUE TITLE
E492: Not an editor command: PickIcons

### ISSUE THREAD

**Issue by kierun** [ziontee113/icon-picker.nvim#9]
![screenshot](https://user-images.githubusercontent.com/3079575/185884792-46831f81-315f-438d-bcda-3216bbc4c6d5.png)

I followed the installation guide (via Packer) and the plug-in installed fine. However, when I try to use it, I get this error.

I am almost convinced it is a problem at my end but I am finding it hard to figure out.  Any chance you could help?

Thank you.

**Comment by ziontee113** [comment]
Hi @kierun, sorry for your difficulties while installing the plugin. `PickIcons` is an old command (deprecated).
The error you're encountering shouldn't keep you from using the Icon Picker.

You can set mappings like here: https://github.com/ziontee113/icon-picker.nvim#usage
If you run into any problems, please let me know

**Comment by kierun** [comment]
I am afraid that those mapping do not work for me: I tried `<Leader><Leader>i` which drops me in insert mode with a `k` next to the cursor. I was trying to use commands to make sure nothing else was wrong.

`:IconPickerInsert alt_font symbols` says `E492: Not an editor command: IconPickerInsert nerd_font`…

**Comment by ziontee113** [comment]
>I tried `<Leader><Leader>i` which drops me in insert mode 

If you want to use the mapping in Normal Mode, use `IconPickerNormal`, not `IconPickerInsert`. If it's still not working, send me your mappings, maybe there's something I can help.
The plugin works just fine on my side so I really don't know what's causing you issues.

**Comment by kierun** [comment]
[It's all here](https://github.com/kierun/dotfiles/tree/main/nvim)… However, I strongly suspect that this configuration is broken in many ways. Been trying to get it updated today and have wasted most of my time. Bah.

Thank you for your help. It is much appreciated!

**Comment by ziontee113** [comment]
You're welcome. If after having your new config and Icon Picker is still not working properly for you, just let me know. I'll help what I can.

**Comment by kierun** [comment]
> You're welcome. If after having your new config and Icon Picker is still not working properly for you, just let me know. I'll help what I can.

After wasting yesterday trying to fix a config that has grown organically for more than a decade, I ditched it, and am starting from nothing. I'll let you know…

**Comment by kierun** [comment]
[With a much cleaned up nvim configuration, things are working fine…](https://github.com/kierun/dotfiles/tree/main/nvim).

Thank you so much for your help and your effort in making this. :+1:
